### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:)

### CODE REVIEW

**Comment by jmastr** [comment]
Thank you very much! Could you change the target branch from master to development please... 

Also we are transitioning to a Qt based build for iOS, Sailfish, and soon also Android. You might want to have a look: https://github.com/micuintus/harbour-Berlin-Vegan/

**Comment by Vistaus** [comment]
How do I change the target branch?

**Comment by jmastr** [comment]
I did it for you: Vistaus wants to merge 1 commit into Berlin-Vegan:development from Vistaus:master

**Comment by Vistaus** [comment]
Okay, thanks for doing it for me :) I will also translate the new Qt app.

**Pull request closed without merging**
