### PR TITLE
updated android sdk, increase version number of third party libs

### PR DESCRIPTION
**Pull request by smeir**
incl needed code changes

### CODE REVIEW

**Comment by jmastr** [comment]
The PR looks good! However, you have three `updated settings for travis` commits. Please stash them into one. You also have a merge node in your branch that is not necessary and not good style. Please remove that.

Btw.: You normally would you present tense and, how I learned lately, start your commit message with uppercase, like `Update settings for travis`.

**Comment by smeir** [comment]
Ok, I will try to stash the commits (never done before), but you are right, the current commit history is not good.
For the "merge node" I will also take a look.

**Comment by ces92** [comment]
During the build process i get around 100 warning, i think most of them are deprecated apis.

**Comment by jmastr** [comment]
We have those warnings since several months. Replacing methods with non-deprecated ones, led on old devices to crashes. We can put annotation there though.

**Comment by smeir** [comment]
I created a new pull request, with better commit history. See #81 . Was to complicated for me clean it up, sorry.  Code is similar, I just updated to even newer versions of third party libs. :-)

**Pull request closed without merging**
